import type { GraphSnapshot } from './types'
export const demoGraph: GraphSnapshot = {
  nodes: [
    { id: 'root', path: '.', kind: 'root', position: [0, 0, 0] },
    {
      id: 'src',
      path: 'src',
      kind: 'directory',
      position: [6.85, 1.2, 0.8],
      activity: { group_key: 'review-ui', last_commit: 'review-ui' },
    },
    {
      id: 'internal',
      path: 'internal',
      kind: 'directory',
      position: [-6.85, -1.2, 0.7],
      activity: { group_key: 'review-core', last_commit: 'review-core' },
    },
    {
      id: 'app',
      path: 'src/App.tsx',
      kind: 'source',
      position: [6.7, 1.7, 1.1],
      activity: {
        group_key: 'review-ui',
        last_commit: 'review-ui',
        last_commit_at: 1784678400,
        last_event: 'commit review-u: add review UI [tool:apply_patch]',
        access_count: 4,
        total_time_ms: 540000,
        lines_added: 118,
        lines_deleted: 24,
        recent_tools: ['apply_patch', 'git commit'],
        session_history: ['review-session-ui'],
        confidence: 'reported+git',
      },
    },
    {
      id: 'scene',
      path: 'src/scene/GraphScene.tsx',
      kind: 'source',
      position: [6.8, 1.3, 1.1],
      activity: {
        group_key: 'review-ui',
        last_commit: 'review-ui',
        access_count: 2,
        total_time_ms: 240000,
        lines_added: 76,
        lines_deleted: 11,
        confidence: 'reported+git',
      },
    },
    {
      id: 'session',
      path: 'internal/session/engine.go',
      kind: 'source',
      position: [-6.7, -1.6, 1.2],
      activity: {
        group_key: 'review-core',
        last_commit: 'review-core',
        access_count: 5,
        total_time_ms: 720000,
        lines_added: 95,
        lines_deleted: 32,
        confidence: 'reported+git',
      },
    },
    {
      id: 'tests',
      path: 'internal/session/engine_test.go',
      kind: 'test',
      position: [-6.8, -1.2, 1.1],
      activity: {
        group_key: 'review-core',
        last_commit: 'review-core',
        access_count: 3,
        total_time_ms: 360000,
        lines_added: 64,
        lines_deleted: 8,
        confidence: 'reported+git',
      },
    },
    {
      id: 'config',
      path: 'wails.json',
      kind: 'config',
      position: [0.5, -6.9, -1.0],
      activity: {
        group_key: 'review-config',
        last_commit: 'review-config',
        access_count: 1,
        total_time_ms: 60000,
        lines_added: 12,
        lines_deleted: 1,
        confidence: 'reported+git',
      },
    },
  ],
  edges: [
    { source: 'root', target: 'src' },
    { source: 'root', target: 'internal' },
    { source: 'root', target: 'config' },
    { source: 'src', target: 'app' },
    { source: 'src', target: 'scene' },
    { source: 'internal', target: 'session' },
    { source: 'internal', target: 'tests' },
  ],
}
